
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 24 14:58:47 EDT 2010
//----------------------------------------------------

package formulaParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 18;
  public static final int STR = 40;
  public static final int EMPTY = 37;
  public static final int OUTPUT = 34;
  public static final int INPUT = 33;
  public static final int LPAREN = 28;
  public static final int MINUS = 14;
  public static final int RPAREN = 27;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int LT = 10;
  public static final int NIN = 22;
  public static final int IN = 21;
  public static final int OR = 3;
  public static final int COMMA = 32;
  public static final int DIV = 17;
  public static final int GEQ = 11;
  public static final int NUM = 38;
  public static final int PLUS = 13;
  public static final int ID = 39;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int TRUE = 35;
  public static final int error = 1;
  public static final int MUL = 15;
  public static final int IMP = 5;
  public static final int EXISTS = 19;
  public static final int MOD = 16;
  public static final int NEQ = 8;
  public static final int EQ = 7;
  public static final int LBRACK = 26;
  public static final int UNION = 23;
  public static final int LBRACE = 29;
  public static final int RBRACK = 25;
  public static final int EQUIV = 6;
  public static final int NEXISTS = 20;
  public static final int RBRACE = 30;
  public static final int LEQ = 12;
  public static final int DIFF = 24;
  public static final int FALSE = 36;
  public static final int GT = 9;
}

